@startuml no2c
start
    :input number;
    if (number < 100000) then (yes)
        :status error;
    else (no)
        :temporary = number % 10;
        :number = Math.floor(number / 10);
        :min = temporary;
        while(number > 0) is (yes)
            :temporary = number % 10;
            if(min >= temporary) then (yes)
                :min = temporary;
            else (no)
            endif
            :number = Math.floor(number / 10);
    endwhile (no)
        :output min;
    endif
end
@enduml