@startuml findMaxOf2DArrayNumbers
start
    #PaleGoldenRod:input arrayNumbers;
    :let maximumNumber = 0;
    :let i = 0;
    while(i < arrayNumbers.length) is (yes)
        :let j = 0;
        while (j < arrayNumbers[i].length) is (yes)
            if(arrayNumbers[i][j] > maximumNumber) then (yes)
                :maximumNumber = arrayNumbers[i][j];
            else (no)
            endif
            :j = j + 1;
        endwhile (no)
        :i = i + 1;
    endwhile (no)
    #PaleGreen:return maximumNumber;
stop
@enduml