@startuml no2a
start
    :input number;
    if (number < 100000) then (yes)
        :status error;
    else (no)
        :temporaryNumber = number % 10;
        :number = Math.floor(number / 10);
        :max = temporaryNumber;
    while(number > 0) is (yes)
        :temporaryNumber = number %10;
        if(temporaryNumber >= max) then (yes)
            :max = temporaryNumber;
        else (no)
        endif
        :number = Math.floor(number / 10);
    endwhile (no)
        :output max;
    endif
end
@enduml