@startuml no2c
start
    :input number;
    if (number < 100000) then (yes)
        :status error;
    else (no)
        :temporaryNumber = number % 10;
        :number = Math.floor(number / 10);
        :min = temporaryNumber;
        while(number > 0) is (yes)
            :temporaryNumber = number % 10;
            if(min >= temporaryNumber) then (yes)
                :min = temporaryNumber;
            else (no)
            endif
            :number = Math.floor(number / 10);
    endwhile (no)
        :output min;
    endif
end
@enduml