@startuml isPrimeNumber
start 
    :input number;
    if (number <= 1) then (yes)
        :return false;
    else (no)
        :let i = 2;
        while (i <= Math.floor(Math.sqrt(number))) is (yes)
            if(number % i === 0) then (yes)
                :return false;
            else (no)
            endif
            :i = i + 1;
        endwhile (no)
        :return true;
    endif
end
@enduml